### PR TITLE
fix: Dependency Requiring CGO

### PR DESCRIPTION
**Pull request by bbernays**
I switched from `Azure/azure-storage-blob-go/azblob` to `Azure/azure-sdk-for-go/sdk/storage/azblob` for the azblob as `azure-storage-blob-go` has been deprecated.

Used the [unreleased version](https://github.com/google/go-cloud/commit/09b10f7359f7776f2befcb7e5d648ebfbbbc3425) `gocloud.dev` package:

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Oh thank you! I guess this will fix #64.

Not sure why CI isn't kicking off... 🤔

**Review by hairyhenderson — APPROVED** [review]

**Comment by hairyhenderson** [comment]
@bbernays can you rebase? I've fixed the CI configuration in #68 and if you rebase it should kick off correctly...

**Comment by bbernays** [comment]
@hairyhenderson - I have rebased, but it seems like I need a maintainer to approve running workflows

**Comment by hairyhenderson** [comment]
Looks like the rebase didn't work quite right - there shouldn't need to be a merge commit in there...

Alternately, can you enable the `Allow edits by maintainers` checkbox?

image

**Comment by hairyhenderson** [comment]
(in the meantime, I have approved the workflows - CI's running now, which is progress! 😉)

**Comment by hairyhenderson** [comment]
@bbernays I'm still seeing commits that shouldn't be here...

Can you do:

```console
$ git fetch upstream
$ git rebase upstream/main
$ git push -f
```

**Comment by bbernays** [comment]
I am closing this pr, because I opened a new [clean PR](https://github.com/hairyhenderson/go-fsimpl/pull/71)

**Pull request closed without merging**
